FROM node:23.9-alpine3.21 AS stage1
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build && npm prune --production

FROM node:23.9-alpine3.21
USER 1000:1000
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_SESSION_TOKEN
ARG ORIGIN
ARG SSO_START_URL
ARG SSO_REGION
WORKDIR /app
COPY --from=stage1 --chown=1000:1000 /app/build ./build
COPY --from=stage1 --chown=1000:1000 /app/node_modules ./node_modules
COPY package.json .
ENV PORT=5050
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
ENV ORIGIN=${ORIGIN}
ENV SSO_START_URL=${SSO_START_URL}
ENV SSO_REGION=${SSO_REGION}
EXPOSE 5050
CMD ["node","build"]